### ISSUE TITLE
'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by hugoh59** [punarinta/react-native-sound-level#7]
I'm getting the following error when trying to build on ios.

> 'React/RCTBridgeModule.h' file not found

I'm using RN 0.60.4 and with autolink but I tried to link it manually and disable autolink for that library and none of these options work. Do you know how to properly use the library for RN 0.60+ ?

**Comment by punarinta** [comment]
I've just done today Android migration for the project from which this lib was split. I think it's time to do the same for iOS. :) Sorry for inconveniences, I'll try to fix this asap.

**Comment by punarinta** [comment]
@hugoh59 do you use CocoaPods when compiling the iOS project? I don't and probably that's why I couldn't reproduce your problem. However I've now added some compatibility code for RN 0.60.x and released a new library version. Could you please fetch it and tell me if it works now?

**Comment by johnny7577** [comment]
<img width="259" alt="螢幕快照 2019-08-06 下午2 50 43" src="https://user-images.githubusercontent.com/21187252/62517278-a74dba80-b859-11e9-878e-b040c71d4761.png">

**Comment by punarinta** [comment]
@johnny7577 a couple questions to you.
1. Do you use CocoaPods or do you build the app without them (see my message above)?
2. Have you tried the new version (1.1.1)?

**Comment by johnny7577** [comment]
> @ johnny7577給你幾個問題。
> 
> 1. 您是否使用CocoaPods或者在沒有它們的情況下構建應用程序（請參閱上面的消息）？
> 2. 你試過新版本（1.1.1）嗎？

1. Not using CocoaPods
2. yes, I use v1.1.1

**Comment by johnny7577** [comment]
I create react-native-sound-level.podspec and add pod 'react-native-sound-level', :podspec => '../node_modules/react-native-sound-level/react-native-sound-level.podspec' on Podfile.
execute pod install 
Solve the problem :)

**Comment by punarinta** [comment]
@johnny7577 awesome!
Now I just need to incorporate your solution into the package somehow.

**Comment by zoruc** [comment]
@punarinta @johnny7577 any update on how to fix this, i'm experiencing the same issue when trying to install

**Comment by NN01010101** [comment]
@johnny7577 can you please share the podspec file? Thank you!
@punarinta would be great to add cocoapod support. BTW. Big thanks on creating this library!

**Comment by NN01010101** [comment]
@zoruc Seems like I managed to get it to work.
So I created the podspec file as @johnny7577 suggested and put it into node_modules/react-native-sound-level/react-native-sound-level.podspec
Here is how the file looks like, maybe @punarinta  you can add it to your future release and update the README:
`require 'json'

package = JSON.parse(File.read(File.join(__dir__, 'package.json')))

Pod::Spec.new do |s|
  s.name         = "react-native-sound-level"
  s.version      = package['version']
  s.summary      = "React Native Sound level library"

  s.authors      = { "Vladimir Osipov" => "vladimir.osipov@gmail.com" }
  s.homepage     = "https://github.com/punarinta/react-native-sound-level"
  s.license      = "Apache License 2.0"
  s.platform     = :ios, "8.0"

  s.source       = { :git => "https://github.com/punarinta/react-native-sound-level" }
  s.source_files  = "ios/**/*.{h,m}"
  s.preserve_paths = "**/*.js"
  s.requires_arc = true
  s.dependency 'React'
end`
Since I previously linked the library, I had to unlink it again with react-native unlink react-native-sound-level
Then cd ios && pod install

I'm using "0.60.4"

**Comment by punarinta** [comment]
@NN01010101 thanks for the solution!
There's this pull request: https://github.com/punarinta/react-native-sound-level/pull/8/commits/cb799af6fc75db34d913a19e80e08104becda20a#diff-fec97c807de4f8a06b87c317a83525ea
Could you please double check it with your environment as well? I'd then merge it in.

**Comment by NN01010101** [comment]
@punarinta I tried the pull request and it didn't work for me. I put the file in the root and in the ios directory and it cocoa pod didn't find it. 
I then tried again with mine podspec by following the steps of @johnny7577 and everything works fine.

**Comment by punarinta** [comment]
@NN01010101 ok, cool. Let me test it that way then.

**Comment by punarinta** [comment]
Solve with a new 1.1.2 release.

**Comment by NN01010101** [comment]
Hey @punarinta, I just removed node-modules, and installed new version 1.1.2 just to make sure everything works well, but it seems like the RNSoundLevel.podspec file does not appear in the directory. How is it possible?

Also, you are missing "pod" in README instructions on iOS, should be:
`Add 'pod react-native-sound-level', :podspec => '../node_modules/react-native-sound-level/RNSoundLevel.podspec' to your ios/Podfile file.`

**Comment by punarinta** [comment]
@NN01010101 it was missing in the package file. :) Try again please (mid the version bump).
